// GENERATED by scripts/build-clips.mjs — do not edit by hand.
// Re-run `npm run assets:clips` after changing the CLIPS array in that script.

export type ClipSource = {
  /** Public paths; the browser picks whichever source it can play. */
  webm: string
  mp4: string
  poster: string
}

export type Clip = {
  id: string
  alt: string
  /** Landscape cut, 2.12:1 — desktop and tablet. */
  wide: ClipSource
  /**
   * 9:16 cut framed on the subject — phones. The wide plate loses about two
   * thirds of its width to `object-cover` in a portrait viewport, which slices
   * whoever is in frame; this is cropped per clip instead.
   */
  portrait: ClipSource
}

export const clips: Clip[] = [
  {
    id: 'gym-stand',
    alt: "Nate standing in the brick gym",
    wide: {
      webm: '/clips/gym-stand.webm',
      mp4: '/clips/gym-stand.mp4',
      poster: '/clips/gym-stand.jpg',
    },
    portrait: {
      webm: '/clips/gym-stand-portrait.webm',
      mp4: '/clips/gym-stand-portrait.mp4',
      poster: '/clips/gym-stand-portrait.jpg',
    },
  },
  {
    id: 'back-squat',
    alt: "Nate under a loaded barbell mid-squat",
    wide: {
      webm: '/clips/back-squat.webm',
      mp4: '/clips/back-squat.mp4',
      poster: '/clips/back-squat.jpg',
    },
    portrait: {
      webm: '/clips/back-squat-portrait.webm',
      mp4: '/clips/back-squat-portrait.mp4',
      poster: '/clips/back-squat-portrait.jpg',
    },
  },
  {
    id: 'coaching',
    alt: "Nate coaching a client through battle ropes",
    wide: {
      webm: '/clips/coaching.webm',
      mp4: '/clips/coaching.mp4',
      poster: '/clips/coaching.jpg',
    },
    portrait: {
      webm: '/clips/coaching-portrait.webm',
      mp4: '/clips/coaching-portrait.mp4',
      poster: '/clips/coaching-portrait.jpg',
    },
  },
  {
    id: 'playa-wall',
    alt: "Nate outside the juice bar",
    wide: {
      webm: '/clips/playa-wall.webm',
      mp4: '/clips/playa-wall.mp4',
      poster: '/clips/playa-wall.jpg',
    },
    portrait: {
      webm: '/clips/playa-wall-portrait.webm',
      mp4: '/clips/playa-wall-portrait.mp4',
      poster: '/clips/playa-wall-portrait.jpg',
    },
  },
  {
    id: 'sweat',
    alt: "Close on Nate mid-set, catching his breath",
    wide: {
      webm: '/clips/sweat.webm',
      mp4: '/clips/sweat.mp4',
      poster: '/clips/sweat.jpg',
    },
    portrait: {
      webm: '/clips/sweat-portrait.webm',
      mp4: '/clips/sweat-portrait.mp4',
      poster: '/clips/sweat-portrait.jpg',
    },
  },
  {
    id: 'arms-up',
    alt: "Nate with arms raised against open sky",
    wide: {
      webm: '/clips/arms-up.webm',
      mp4: '/clips/arms-up.mp4',
      poster: '/clips/arms-up.jpg',
    },
    portrait: {
      webm: '/clips/arms-up-portrait.webm',
      mp4: '/clips/arms-up-portrait.mp4',
      poster: '/clips/arms-up-portrait.jpg',
    },
  },
  {
    id: 'beach',
    alt: "Nate outdoors by the water",
    wide: {
      webm: '/clips/beach.webm',
      mp4: '/clips/beach.mp4',
      poster: '/clips/beach.jpg',
    },
    portrait: {
      webm: '/clips/beach-portrait.webm',
      mp4: '/clips/beach-portrait.mp4',
      poster: '/clips/beach-portrait.jpg',
    },
  },
]

/** Shown before any clip can play, and as the reduced-motion still. */
export const heroPoster = clips[0].wide.poster
export const heroPosterPortrait = clips[0].portrait.poster

/** Standalone 4:5 still for the Meet Nate section. */
export const natePortrait = '/clips/nate-portrait.jpg'
