// GENERATED by scripts/build-clips.mjs — do not edit by hand.
// Re-run `npm run assets:clips` after changing the CLIPS array in that script.

export type Clip = {
  id: string
  /** Public paths; the browser picks whichever source it can play. */
  webm: string
  mp4: string
  poster: string
  alt: string
}

export const clips: Clip[] = [
  {
    id: 'gym-stand',
    webm: '/clips/gym-stand.webm',
    mp4: '/clips/gym-stand.mp4',
    poster: '/clips/gym-stand.jpg',
    alt: "Nate standing in the brick gym",
  },
  {
    id: 'back-squat',
    webm: '/clips/back-squat.webm',
    mp4: '/clips/back-squat.mp4',
    poster: '/clips/back-squat.jpg',
    alt: "Nate under a loaded barbell mid-squat",
  },
  {
    id: 'coaching',
    webm: '/clips/coaching.webm',
    mp4: '/clips/coaching.mp4',
    poster: '/clips/coaching.jpg',
    alt: "Nate coaching a client through battle ropes",
  },
  {
    id: 'playa-wall',
    webm: '/clips/playa-wall.webm',
    mp4: '/clips/playa-wall.mp4',
    poster: '/clips/playa-wall.jpg',
    alt: "Nate outside the juice bar",
  },
  {
    id: 'sweat',
    webm: '/clips/sweat.webm',
    mp4: '/clips/sweat.mp4',
    poster: '/clips/sweat.jpg',
    alt: "Close on Nate mid-set, catching his breath",
  },
  {
    id: 'arms-up',
    webm: '/clips/arms-up.webm',
    mp4: '/clips/arms-up.mp4',
    poster: '/clips/arms-up.jpg',
    alt: "Nate with arms raised against open sky",
  },
  {
    id: 'beach',
    webm: '/clips/beach.webm',
    mp4: '/clips/beach.mp4',
    poster: '/clips/beach.jpg',
    alt: "Nate on the beach at the water line",
  },
]

/** Smallest clip — used alone on mobile and under save-data. */
export const lightestClip: Clip = clips.find((c) => c.id === 'arms-up') ?? clips[0]

/** Shown before any clip can play, and as the reduced-motion still. */
export const heroPoster = clips[0].poster
